site_name: WFV Documentation
theme_dir: 'mkdocs-material/material'
repo_name: 'macder/wp-form-validation'
repo_url: 'https://github.com/macder/wp-form-validation'

pages:
    - Welcome: index.md
    - Overview: overview.md
    - Getting Started: start.md
    - Quick Guide: quick-guide.md
    - User Guide:
        - 'Hooks': guide/hooks.md
        - 'Create': guide/create.md
        - 'Rules': guide/rules.md
        - 'Messages': guide/messages.md
        - 'Populate': guide/populate.md
        - 'Input': guide/input.md
        - 'Errors': guide/errors.md
    - Examples:
        - 'Basic': examples/basic.md

extra:
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'Open Sans'
    code: 'Source Code Pro'

google_analytics:
  - 'UA-98676146-1'
  - 'auto'


markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - meta
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
